# Setup
title:               Big Waves
tagline:             'The winds and the waves are always on the side of the ablest navigators.'
description:         '#Programming #CleanCode'
url:                 https://ihanchoi.github.io
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              IHan Choi
  url:               https://github.com/ihanchoi
  email:             ihanchoi.dev@gmail.com

# Gems
plugins:
  - jekyll-paginate
  - jemoji
# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y

future: true

