# Setup
title:               Log
tagline:             'Theme'
description:         '#Programming #CleanCode'
url:                 https://ihanchoi.github.io
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Mark Otto
  url:               abcdtest
  email:             testtestdev@gmail.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y

future: true

